### ISSUE TITLE
Make sure chip.nearest_ethernet exists

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNMachine#91]
There is an issue that when you create a chip the nearest ethernet chip may not yet have been created.

So there is no way of knowing of this chip actually really exists.

This could result in Chip.nearest_ethernet_x giving incorrect information which has to be dealt with elsewhere. This leads to inconsistency and possibly even error.

The idea is to make Chip slightly modifiable but with some safety code.

1. Every chip has an extract boolean flag. Ethernet validated which defaults to False.

2. Add a validate Ethernet method which checks that the ethernet the chip thinks it has is exists.
a. If yes set validated flag True
b. If no change the chips ethernet to an existing default. 
i. check if already validated in which case go pop
ii. set change ethernet default
iii. set validated flag to true

3. Extend the nearest_ethernet... method to include a check on validated

**Comment by Christian-B** [comment]
Looking at GetMachineProcess it already caches all ChipInfo Objects.

So an viable alternative is to first build a list of the Ethernet chips and then a list of the None ethernet chips. Using the default if a Chips Ethernet does not actually exist.

Then either concat the two lists or change the machine constructor tow get two lists of chips.

This approach however will permanently change the order that the Chips are in!

**Comment by Christian-B** [comment]
Either way if a chip does not have a its normal ethernet the system should go POP if enable_advanced_monitor_support = True

**Comment by alan-stokes** [comment]
3 things.
1. machine and chip should be unmutable, so any plan that keeps that is more preferable to me than having the chip/machine mutable.
2. The order of the chips, couldn't a sort be introduced to ensure its the same (or at least consistent from now on)? Furthermore if the info is cached, why not cache them all, then run though each chip as we currently do, and do whatever checks you do before building that individual chip's nearest ether x and y?
3. whats the default if it doesn't exist? this is not clear and on a say 12 board machine, where only 2 of them have Ethernet, which is considered the default? is there a default? or should there be a load balancing effect here?

**Comment by alan-stokes** [comment]
2. id assume chipInfo was written to be unmutable. but muting that given that the real chip needs to be modded........ there's a thought there that says you should update the real chips SDRAM data with correct data and then reread it....but i can see that's unoptimal in performance, more data to the board, but we might need to do that for completeness. yuck. So yea, make that inmutable is probabily ok for the time being....... maybe

3. i was more on the point that your saying when ya build the machine, not when its used by say extra monitor building. everything above the machine kinda assumes the machine is set up correctly and optimally. Which is why i think the issue sits here. If i had 12 boards, 2 ethernets and only 1 was being used to feed 11 boards, id say thats majorly bad. its also a problem for the fixed route stuff, i dont think itll handle you moving ethernets for a given board. I think we agreed that the use case of 12 boards to 2 etherents or akin were not worth considereing.... so if ya fix it here, you'll need to fix it there as well i fear.

**Comment by Christian-B** [comment]
I plan to give the Machine class a flag to say if it has any Chips where the "nearest ethernet" is not on that board.  

Anything that requires all chips to have an on board ethernet will then refuse to work!

We could even consider a config flag set to False by default. So that Off board Ethernet are only allowed if the user specifically says so.   So in the case of a three board system where on wire fell out the system goes pop.

If a user wants to use a weird combination of board they have to specifically says so and also tweak other flags like enable_advanced_monitor_support.

The 12 board 2 ethernet problem can be crossed if needed. But doing the adaption at or just before Machine creation makes sure it is in one place and not squirreled away in lots of different places or just forgotten.

**Comment by alan-stokes** [comment]
"The 12 board 2 ethernet problem can be crossed if needed. But doing the adaption at or just before Machine creation makes sure it is in one place and not squirreled away in lots of different places or just forgotten."

i concur, which is why its a design decision at this point. not higher up. 

using a flag, ok. whenever you make the error message related to it, you might want to state that it could be fixed if ya do ........

just so we remember in future. Id put it in ASB to be honest. as that could be a central place for these checks, instead of on every algorithm that uses the machine and ethernets. But that adds to the monster that is ASB.......so maybe.

**Comment by Christian-B** [comment]
Places found that do strange ethernet chip missing.

https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/utilities/utility_objs/resource_tracker.py

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/extractor2/spinn_front_end_common/interface/ds/ds_sqllite_database.py

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/interface_functions/insert_edges_to_live_packet_gatherers.py

Places that just assume ethernet is present. (eventually causing a null pointer exception)

https://github.com/SpiNNakerManchester/PACMAN/blob/extractor2/pacman/utilities/file_format_converters/convert_to_java_machine.py

https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/tree/master/spinnaker_graph_front_end/examples/test_extra_monitor_core_data_extraction

https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/tree/master/spinnaker_graph_front_end/examples/test_extra_monitor_core_data_extraction_multiple_locations

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/blob/master/spinn_front_end_common/interface/interface_functions/insert_edges_to_extra_monitor_functionality.py

 .....

**Comment by Christian-B** [comment]
Work in progress
https://github.com/SpiNNakerManchester/SpiNNMan/tree/ethernet_checker

This either throws an Exception or changes the ChipSummaryInfo BEFORE a chip or machine is created.
It uses a simple algorithm that just uses 0,0 or missing that the first Ethernet it happens to find.

Next step is to change MachineGenerator to use a config to set enforceOnBoardEthernet

**Comment by Christian-B** [comment]
Suggest postponing until after release as could effect various places.

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/SpiNNMachine/pull/104 now adds a validate function to machine.
This now checks that all ethernet chips exist and that they are all at 0,0.

https://github.com/SpiNNakerManchester/SpiNNMan/pull/161 calls validate after a machine is created by GetMachineProcess  which is used both for spalloc and local boards.

https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/435 adds validate to VirtualMachineGenerator so virtual machines created from cfg are also checked.

VirtualMachines created in code are NOT checked to avoid SpallocMaxMachineGenerator having to do lots of checks. But the unittests for virtual machine do validate so the code is correct.

So all machines a user can get without doing something weird will have all ethernetchip existing and at local 0,0

**Comment by Christian-B** [comment]
https://github.com/SpiNNakerManchester/PACMAN/blob/master/pacman/utilities/utility_objs/resource_tracker.py   _get_matching_ip_tag

Does so things to find an IP tag on a different board?
Unsure if this still makes sense.

**Comment by Christian-B** [comment]
Assigning to Rolwye to doublke check the resource tracker get>matching_ip_tags stuff is not broken and then to close.

**Comment by rowleya** [comment]
I have had a look at this and it looks like it should be OK.  The purpose of this function is to use an existing tag allocation if possible, but also to allow the tag to be allocated on the board of the placement rather than using an Ethernet on another chip.  So basically, if the tag can be allocated on the board of the placement, claim there is no existing tag, otherwise use an existing tag if there is one, otherwise allow allocation of a new tag.  This is independent of whether Ethernet chips exist or not.
